// video js
function deferVideo() {

    //defer html5 video loading
    $("landingpage3web.webm").each(function() {
      var sourceFile = $(this).attr("data-src");
      $(this).attr("src", sourceFile);
      var video = this.parentElement;
      video.load();
     
    //video.play();
    });
    
    }
    window.onload = deferVideo;
const words = ["Cryptic Corridor", "Lachrymose Lullaby", "Shadowed Souls", "Aching Abyss", "Funeral Fervor", "Melancholic Melodies", "Despairing Depths", "Blackened Blight", "Grieving Graves", "Elegiac Embrace", "Wounded Wraiths", "Tearful Trance", "Lamenting Lorelei", "Sorrowful Solitude", "Desolate Descent", "Tragic Tenderness", "Forsaken Fog", "Haunted Hymn", "Dolorous Dirge", "Tearstained Tome", "Mourning Muse", "Ghostly Grief", "Shadowed Sorrows", "Wounded Whisperers", "Despairing Drums", "Blackened Bloom", "Abyssal Anguish", "Elegiac Echoes", "Cryptic Crucible", "Melancholic Miasma", "Drowning Dystopia", "Lonesome Lament", "Sullen Serenity", "Funereal Frenzy", "Morose Mirage", "Graveyard Grace", "Desolate Dreamscape", "Tragic Trepidation", "Elegiac Endings", "Ashen Whisper", "Solitary Serenade", "Cursed Elegy", "Midnight Mourning", "Funeral Fugue", "Melancholic Moon", "Death's Lullaby", "Blackened Ballad", "Grieving Ghosts", "Eulogic Echo", "Mourning Mist", "Wilted Willows", "Cryptic Cries", "Lamenting Lilies", "Mournful Mirage", "Sorrowful Symphony", "Desolate Dirge", "Tragic Tale", "Forsaken Fates", "Haunted Heartstrings", "Mysticarium", "Shadowlark", "Necrosiren", "Esoterrific", "Etherium", "Wraithlily", "Arcanique", "Celestiadore", "Abyssalight", "Crypticorner", "Lunariscope", "Witchsoul", "Enchantetica", "Crimsonquill", "Occultive", "Moonshadowed", "Shadowstream", "Celestialia", "Necrologix", "Darkentangle", "Mystic Echoes", "Shadowland Saints", "Necroantics", "Esoteric Expanse", "Ethereal Embrace", "Wraithsong", "Arcane Avenue", "Celestial Circuit", "Abyssal Aura", "Cryptic Current", "Lunar Lullaby", "Witching Hourglass", "Enchanted Eden", "Crimson Cadence", "Occult Oasis", "Moonlit Medley", "Shadow Symphony", "Celestial Chorus", "Necrotic Nostalgia", "Acherontia", "Nyctophiliac", "Occultistix", "Darkmagus", "Chthonica", "Cryptosynthesis", "Necroticus", "Elysiumn", "Noctivagant", "Shadowthorn", "Abysstique", "Nightfallen", "Phasmatica", "Mysterionix", "Thaumaturgix", "Necrocryptic", "Infernalis", "Demonomicon", "Xylophage", "Nethermancer", "Spectralium", "Nekrosynth", "Nocturnica", "Cryptomancer", "Phantasmagoria", "Asphodelia","Necroscopium",
  "Abyssium",
  "Eclipsion",
  "Xylorite",
  "Occultant",
  "Obscuric",
  "Wraithen",
  "Infernum",
  "Nightwitch",
  "Hermetica",
  "Cryptonite",
  "Demonicus",
  "Necrotica",
  "Mortiferum",
  "Azurael",
  "Necronaut",
  "Voidseeker",
  "Cthonic",
  "Erebos",
  "Necromorph",
  "Nefariousia",
  "Abysm",
  "Sorcera",
  "Thantos",
  "Cryptovore",
  "Nyctophile",
  "Lumineth",
  "Occultra",
  "Grimmoire",
  "Daemonium",
  "Vesperia",
  "Nightshadean",
  "Heretica",
  "Anubium",
  "Spectralium",
  "Nekrosynth",
  "Nocturnica",
  "Cryptomancer",
  "Phantasmagoria",
  "Asphodelia",
  "Necroscopium",
  "Abyssium",
  "Eclipsion",
  "Xylorite",
  "Occultant",
  "Obscuric",
  "Wraithen",
  "Infernum",
  "Nightwitch",
  "Hermetica",
  "Cryptonite",
  "Demonicus",
  "Necrotica",
  "Mortiferum",
  "Acherontia",
  "Nyctophiliac",
  "Occultistix",
  "Darkmagus",
  "Chthonica",
  "Cryptosynthesis",
  "Necroticus",
  "Elysiumn",
  "Noctivagant",
  "Shadowthorn",
  "Abysstique",
  "Nightfallen",
  "Phasmatica",
  "Mysterionix",
  "Thaumaturgix",
  "Necrocryptic",
  "Infernalis",
  "Demonomicon",
  "Xylophage",
  "Nethermancer",
  "Mystic Echoes",
  "Shadowland Saints",
  "Necroantics",
  "Esoteric Expanse",
  "Ethereal Embrace",
  "Wraithsong",
  "Arcane Avenue",
  "Celestial Circuit",
  "Abyssal Aura",
  "Cryptic Current",
  "Lunar Lullaby",
  "Witching Hourglass",
  "Enchanted Eden",
  "Crimson Cadence",
  "Occult Oasis",
  "Moonlit Medley",
  "Shadow Symphony",
  "Celestial Chorus",
  "Necrotic Nostalgia",
  "Darkened Duet",
  "Mysticarium",
  "Shadowlark",
  "Necrosiren",
  "Esoterrific",
  "Etherium",
  "Wraithlily",
  "Arcanique",
  "Celestiadore",
  "Abyssalight",
  "Crypticorner",
  "Lunariscope",
  "Witchsoul",
  "Enchantetica",
  "Crimsonquill",
  "Occultive","Moonshadowed",
  "Shadowstream",
  "Celestialia",
  "Necrologix",
  "Darkentangle",
  "Tearstained Tome",
  "Mourning Muse",
  "Ghostly Grief",
  "Shadowed Sorrows",
  "Wounded Whisperers",
  "Despairing Drums",
  "Blackened Bloom",
  "Abyssal Anguish",
  "Elegiac Echoes",
  "Cryptic Crucible",
  "Melancholic Miasma",
  "Drowning Dystopia",
  "Lonesome Lament",
  "Sullen Serenity",
  "Funereal Frenzy",
  "Morose Mirage",
  "Graveyard Grace",
  "Desolate Dreamscape",
  "Tragic Trepidation",
  "Elegiac Endings",
  "Mourning Mistral",
  "Cryptic Corridor",
  "Lachrymose Lullaby",
  "Shadowed Souls",
  "Aching Abyss",
  "Funeral Fervor",
  "Melancholic Melodies",
  "Despairing Depths",
  "Blackened Blight",
  "Grieving Graves",
  "Elegiac Embrace",
  "Wounded Wraiths",
  "Tearful Trance",
  "Lamenting Lorelei",
  "Sorrowful Solitude",
  "Desolate Descent",
  "Tragic Tenderness",
  "Forsaken Fog",
  "Haunted Hymn",
  "Dolorous Dirge",
  "Azurael",
  "Necronaut",
  "Voidseeker",
  "Cthonic",
  "Erebos",
  "Necromorph",
  "Nefariousia",
  "Abysm",
  "Sorcera",
  "Thantos",
  "Cryptovore",
  "Nyctophile",
  "Lumineth",
  "Occultra",
  "Grimmoire",
  "Daemonium",
  "Vesperia",
  "Nightshadean",
  "Heretica",
  "Anubium",
  "Euphonicide",
  "Crystalline",
  "Necroverse",
  "Shadowlore",
  "Arcanum",
  "Celestica",
  "Lunarity",
  "Occultus",
  "Mystica",
  "Abyssia",
  "Witchwood",
  "Enchanta",
  "Crimsonium",
  "Esoterra",
  "Moonshade",
  "Shadowkind",
  "Cryptica",
  "Celestion",
  "Necrosphere",
  "Darkenstar",
  "Euphoric Exorcism",
  "Crystal Cathedral",
  "Necrotic Nexus",
  "Shadowed Symphony",
  "Arcane Aria",
  "Celestial Citadel",
  "Lunar Lycanthropy",
  "Occult Odyssey",
  "Mystic Mirage",
  "Abyssal Aberration",
  "Witching Wyvern",
  "Enchanted Enclave",
  "Crimson Cryptogram",
  "Esoteric Epoch",
  "Moonlit Mandala",
  "Shadowy Solace",
  "Cryptic Conduit",
  "Celestial Cynosure",
  "Necrotic Nocturne",
  "Darkened Dominion",
  "Spectral Seraglio",
  "Crimson Cryptid",
  "Moonlit Mausoleum","Coven of the Crystalline Catacombs",  "Occult Oblivion",  "Arcane Alchemy",  "Twilight Thaumaturgy",  "Necrotic Netherworld",  "Abyssal Ascent",  "Witching Wasteland",  "Esoteric Elixir",  "The Cryptic Curator",  "Shadowed Synapse",  "Enchanted Eclipse",  "Mystic Mirage",  "Celestial Covenants",  "Cryptic Cabaret",  "Lunar Levitation",  "Darkened Divinity",  "Cosmic Conjurer",  "Moonlit Monastery",  "Shadow Coven",  "Witching Hourglass",  "Blood Rituals",  "Midnight Oracle",  "Esoteric Empress",  "Crystal Catacombs",  "Celestial Cenotaph",  "Occult Opulence",  "Arcane Asylum",  "Veiled Visions",  "Necrotic Nirvana",  "Spectral Sanctuary",  "Darkened Delirium",  "Lunar Labyrinth",  "Eternal Euphoria",  "Enchanted Exile",  "Mystic Menagerie",  "Cryptic Cosmos",  "Cosmic Catastrophe",  "Demonic Serenade",  "Veil of Mourning",  "Grim Harvest",  "Coven of the Blackened Sun",  "Death's Whisper",  "Shadowed Omen",  "Ghostly Requiem",  "Necromantic Symphony",  "Cryptic Covenant",  "Nightfall Syndicate",  "Ashen Altar",  "Voidbound Legacy",  "Phantom Hymn",  "Wraiths of Despair",  "Lunar Lament",  "Occultist's Odyssey",  "Crimson Chamber Choir",  "Abyssal Anthem",  "Cryptic Cryptid",  "Ephemeral Eclipse",  "Blackmoon Oracle",  "Nightshade Syndicate",  "Bloodmoon Cult",  "Darkwater Saints",  "Death's Embrace",  "Ashen Veil",  "Shadowbound Ritual",  "Bonechapel Legacy",  "Necrotic Hymn",  "Phantom Limb Theatre",  "Wraithsong Covenant",  "Voidwalker Symphony",  "Lunar Ecstasy",  "Occultist's Lament",  "Blackened Heart Society",  "Scarlet Chamber Orchestra",  "Abyssal Chant",  "Cryptic Carnival",  "Infernal Orchestra",  "Eerie Euphony",
  "Mystic Manor", "Obsidian Oasis", "Enchanted Enclave", "Shadowed Sanctum", "Celestial Citadel", "Cryptic Cabal", "Necrotic Nexus", "Arcane Assembly", "Twilight Temple", "Lunar Lodge", "Esoteric Enigma", "Abyssal Abode", "Mystic Masquerade", "Enchanted Embassy", "Shadowed Citadel", "Celestial Circle", "Cryptic Conclave", "Necrotic Nook", "Arcane Alliance", "Twilight Tribunal", "Lunar Library", "Esoteric Estate", "Abyssal Assemblage", "Mystic Mansion", "Enchanted Emporium", "Shadowed Stronghold", "Celestial Court", "Cryptic Council", "Necrotic Nest", "Arcane Agency"];

      // Define a function to get a random word from the array and display it
      function getRandomWord() {
        // Generate a random index between 0 and the length of the array
        const index = Math.floor(Math.random() * words.length);
        // Get the word at the random index
        const word = words[index];
        // Display the word in the "random-word" paragraph element
        document.getElementById("random-word").textContent = word;
      }